name: ai_assistant
description: An AI Assistant (ChatBot, Image Generator & Language Translator) App Based on ChatGPT developed by Harsh H. Rajpurohit 

publish_to: 'none' 

# App Version
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # App Write Database (For dynamically getting API Key)  
  # appwrite: ^11.0.1s
  appwrite: 
    path: ./appwrite

  # iOS Styled Icons
  cupertino_icons: ^1.0.2

  # For using Lottie Animations
  lottie: ^2.7.0

  # For Hive Database
  # hive: ^4.0.0-dev.2
  # isar_flutter_libs: ^4.0.0-dev.13

  # Using this version due to less apk size
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For Accessing Storage Path
  path_provider: ^2.1.1

  # For State Management
  get: ^4.6.6

  # For Custom Animation
  flutter_animate: ^4.2.0+1
  animated_text_kit: ^4.2.2

  # For API Call
  http: ^1.1.0

  # For AI Image Generation
  dart_openai: ^5.0.0
  cached_network_image: ^3.3.0

  # For Google Language Translate
  translator_plus: ^1.0.1

  # For Sharing Image
  share_plus: ^7.2.1

  # Facebook Ads
  easy_audience_network: ^0.0.6

  dio: ^5.0.0
  chat_gpt_sdk: ^3.0.1
  dash_chat_2: ^0.0.18
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  google_nav_bar: ^5.0.6
  tflite_flutter: ^0.9.0
  image_picker: ^0.7.4
  camera: any
  tflite_flutter_helper: any
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  animate_do: ^3.0.2
  audioplayers: ^5.2.1
  gallery_saver_updated: ^3.0.0
  epub_view: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Encourages Good Practices
  flutter_lints: ^2.0.0

  # For Changing App Icon
  # icons_launcher: ^2.1.4

flutter:

  # Enables Material Design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/
    - assets/images/
    - assets/sounds/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
